env:
  browser: true,
  commonjs: true,
  es6: true
  node: true
  jest: true
extends: airbnb
parser: 'babel-eslint'
plugins:
  - react
  - jsx-a11y
  - import
rules:
  no-use-before-define:
    - error
    - { functions: false, classes: true }
  func-names:
    - warn
    - never
  indent:
    - error
    - 2
  class-methods-use-this: 0
  no-return-assign: 0
  no-confusing-arrow: 0
  no-shadow: 0
  no-plusplus: 0
  no-prototype-builtins: 0
  padded-blocks: 0
  no-unused-vars: 1
  react/prop-types: 0
  react/jsx-filename-extension: 0
  react/no-unescaped-entities: 0
  react/prefer-stateless-function: 1
  react/no-array-index-key: 0
  jsx-a11y/href-no-hash: 0
